name = "creative-agency-portfolio"
compatibility_date = "2023-12-01"
node_compat = true

[build]
command = "npm run build"
pages_build_output_dir = ".next"

[site]
bucket = ".next"

[build.environment]
NODE_VERSION = "20.10.0" 