name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug Info
        run: |
          echo "Current directory contents:"
          ls -la
          echo "CNAME content:"
          cat CNAME
          echo "index.html exists:"
          if [ -f "index.html" ]; then echo "Yes"; else echo "No"; fi
          echo "Workspace directory: $GITHUB_WORKSPACE"
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true 